/* Noah · Unit 2: Renaissance, Reformation and Scientific Revolution · test Wed Sep 30, 2026 */
window.GUIDE = {
  id: "noah-unit2",
  student: "Noah",
  subject: "Unit 2",
  start: "2026-09-21",
  days: [
    {title:"A changing world", kind:"learn"},
    {title:"Renaissance ideas", kind:"learn"},
    {title:"Art and the printing press", kind:"learn"},
    {title:"The Reformation begins", kind:"learn"},
    {title:"The Reformation spreads", kind:"learn"},
    {title:"The Scientific Revolution", kind:"learn"},
    {title:"The big picture", kind:"connect"},
    {title:"Review day 1", kind:"review"},
    {title:"Review day 2", kind:"final"},
    {title:"Test day", kind:"test"}
  ],
  groups: [
    {key:"R", name:"Renaissance"},
    {key:"F", name:"Reformation"},
    {key:"S", name:"Scientific Revolution"}
  ],

  /* day = which learn day (1-based) the card opens on. kind: person | place | idea. auto:false = no auto-generated questions. */
  terms: [
    {id:"renaissance",day:1,group:"R",kind:"idea",term:"Renaissance",
     def:"A period of “rebirth” in Europe marked by a renewed interest in art and learning.",
     short:"Rebirth of art and learning in Europe",
     hook:"Re-naissance = re-birth. Europe got curious again about art, learning, and ancient Greece and Rome."},
    {id:"constantinople",day:1,group:"R",kind:"place",term:"Constantinople",
     def:"A major city that served as the capital of the Byzantine Empire until it was captured by the Ottoman Empire.",
     short:"Byzantine capital captured by the Ottomans",
     hook:"Captured in 1453. Today the city is called Istanbul. Its fall is a classic turning point."},
    {id:"ottoman",day:1,group:"R",kind:"place",article:"the",term:"Ottoman Empire",
     def:"A large and powerful empire that captured Constantinople and controlled trade routes between Europe and Asia.",
     short:"Empire that controlled Europe–Asia trade routes",
     hook:"Think toll booth: the Ottomans sat between Europe and Asia, so trade had to pass through them."},
    {id:"turning",day:1,group:"R",kind:"idea",term:"Turning point",
     def:"A major event that causes a significant change in the course of history.",
     short:"Event that changes the course of history",
     hook:"Like a plot twist in a movie: after it, the story heads in a new direction. Examples: the fall of Constantinople, the printing press."},

    {id:"humanism",day:2,group:"R",kind:"idea",term:"Humanism",
     def:"An intellectual movement during the Renaissance that focused on human potential and achievements.",
     short:"Focus on human potential and achievements",
     hook:"HUMAN-ism is about humans: what people can do, create, and figure out."},
    {id:"secular",day:2,group:"R",kind:"idea",term:"Secular",
     def:"Worldly or non-religious; relating to life on Earth rather than spiritual matters.",
     short:"Worldly, not religious",
     hook:"A painting of a merchant's family is secular. A painting of an angel is religious."},
    {id:"medici",day:2,group:"R",kind:"person",plural:true,article:"the",term:"Medici family",
     def:"A powerful and wealthy family in Florence that supported many Renaissance artists.",
     short:"Rich Florence family that paid artists",
     hook:"Medici = money. They were bankers who acted like sponsors (patrons) for artists."},
    {id:"inquiry",day:2,group:"R",kind:"idea",term:"Inquiry",
     def:"A process of asking questions and searching for the truth through observation and evidence.",
     short:"Asking questions, finding truth with evidence",
     hook:"Inquiry comes from “inquire,” which means to ask. Ask, observe, find evidence."},

    {id:"leonardo",day:3,group:"R",kind:"person",term:"Leonardo da Vinci",
     def:"A famous Renaissance artist, inventor, and scientist known for works like the Mona Lisa.",
     short:"Artist and inventor who painted the Mona Lisa",
     hook:"The ultimate “Renaissance man”: painter, inventor, and scientist all in one. Spelling check: Leonardo da Vinci."},
    {id:"michelangelo",day:3,group:"R",kind:"person",term:"Michelangelo",
     def:"A famous Renaissance sculptor and painter known for the statue of David and painting the Sistine Chapel ceiling.",
     short:"Sculpted David, painted the Sistine Chapel ceiling",
     hook:"Michelangelo = marble and ceiling. David is the statue, the Sistine Chapel is the ceiling."},
    {id:"perspective",day:3,group:"R",kind:"idea",term:"Perspective",
     def:"An art technique that creates the appearance of depth on a flat surface.",
     short:"Art technique that shows depth on a flat surface",
     hook:"Railroad tracks look like they meet far away. Renaissance painters copied that trick."},
    {id:"gutenberg",day:3,group:"R",kind:"person",term:"Gutenberg",
     def:"The inventor of the printing press, which helped spread information quickly.",
     short:"Inventor of the printing press",
     hook:"Person = Gutenberg. Machine = printing press. Don't mix up the inventor and the invention."},
    {id:"press",day:3,group:"R",kind:"idea",term:"Printing press",
     def:"A machine that made it much faster and cheaper to print books and spread ideas.",
     short:"Machine that printed books fast and cheap",
     hook:"The internet of the 1400s. Before it, books were copied by hand. After it, ideas like Luther's spread everywhere."},

    {id:"luther",day:4,group:"F",kind:"person",term:"Martin Luther",
     def:"A German monk who started the Reformation by criticizing the Catholic Church.",
     short:"Monk who started the Reformation",
     hook:"Not Martin Luther King Jr.! This Martin Luther lived 1483–1546, more than 400 years earlier. He wanted people to read the Bible in their own language.",
     ask:"Did he have any kids? Yes. He married Katharina von Bora and they had six children."},
    {id:"theses",day:4,group:"F",kind:"idea",term:"95 Theses",
     def:"A list of powerful arguments written by Martin Luther criticizing the practices and corruption of the Catholic Church.",
     short:"Luther's list of arguments against Church practices",
     hook:"Posted in October 1517. A thesis is an argument, so 95 theses = 95 arguments. A big one: stop selling indulgences."},
    {id:"indulgence",day:4,group:"F",kind:"idea",term:"Indulgence",
     def:"A payment to the Church that people believed would forgive their sins.",
     short:"Payment to the Church to forgive sins",
     hook:"Like trying to buy a “get out of sin free” card. Luther said forgiveness can't be bought."},
    {id:"reformation",day:4,group:"F",kind:"idea",term:"Reformation",
     def:"A movement that led to the creation of new Christian churches separate from the Catholic Church.",
     short:"Movement that created new Christian churches",
     hook:"Re-FORM-ation: people wanted to reform (fix) the Church. It ended up splitting instead."},
    {id:"protestant",day:4,group:"F",kind:"idea",term:"Protestant",
     def:"A follower of any of the Western Christian churches that are separate from the Roman Catholic Church.",
     short:"Christian in a church separate from the Catholic Church",
     hook:"Protest-ant: they protested against the Catholic Church."},
    {id:"worms",day:4,group:"F",kind:"idea",term:"Diet of Worms",
     def:"A meeting in 1521 where Luther was ordered to take back his ideas. He refused, was pushed out of the Church, and had to go into hiding.",
     short:"1521 meeting where Luther refused to back down",
     hook:"No worms were eaten. A “diet” was a formal meeting, and Worms is a city in Germany.",
     ask:"How long was he hiding? About ten months, in Wartburg Castle. He used the time to translate the New Testament into German."},

    {id:"henry",day:5,group:"F",kind:"person",term:"Henry VIII",
     def:"A famous English king who broke away from the Catholic Church to start the Church of England.",
     short:"King who started the Church of England",
     hook:"The pope wouldn't end Henry's marriage, so Henry made his own church and put himself in charge."},
    {id:"calvin",day:5,group:"F",kind:"person",term:"John Calvin",
     def:"An important Reformation leader who established Reformed Christianity and taught predestination.",
     short:"Reformation leader who taught predestination",
     hook:"Like Luther, Calvin taught that people are saved by faith, not actions. What makes Calvin different is predestination.",
     ask:"Why was he forced to leave France? France was Catholic and punished Protestants, so he fled to Geneva, Switzerland."},
    {id:"predestination",day:5,group:"F",kind:"idea",term:"Predestination",
     def:"The belief that God has already decided who will be saved.",
     short:"Belief that God already chose who is saved",
     hook:"PRE-destination: your destination is decided pre (before) you are even born. This is Calvin's signature idea."},
    {id:"huguenots",day:5,group:"F",kind:"person",plural:true,article:"the",term:"Huguenots",
     def:"French Protestants who followed Calvin's ideas. They took root in the 1500s, gained political power, fought in religious wars, and many left France for religious freedom.",
     short:"French Protestants who followed Calvin",
     hook:"Huguenots: French, and not Catholic. Many left France to find religious freedom."},
    {id:"map",day:5,group:"F",kind:"idea",auto:false,term:"Map of the Reformation",
     def:"The Reformation split Europe. Lutherans held a lot of land, Catholics still held a lot, and small groups like the Unitarians held very little.",
     short:"Europe split into Catholic and Protestant lands",
     hook:"Big picture: much of northern Europe turned Protestant while much of southern Europe stayed Catholic. Spelling check: Unitarians."},
    {id:"art",day:5,group:"F",kind:"idea",auto:false,term:"Art of the Reformation",
     def:"Many Protestants opposed religious images and discouraged praying to statues. Radical groups destroyed Catholic art, and artists turned to scenes of daily life and civic pride.",
     short:"Daily life and civic pride instead of religious images",
     hook:"Fewer saints and statues, more paintings of regular people, towns, and everyday life.",
     ask:"Why daily life instead of religious scenes? Protestant churches didn't want religious images, so artists painted what people would still buy: everyday life and their proud cities."},

    {id:"scirev",day:6,group:"S",kind:"idea",term:"Scientific Revolution",
     def:"A time of great scientific discovery when people started using experiments and logic to understand the world.",
     short:"Era of experiments and logic",
     hook:"Same spirit as inquiry: don't just trust old books. Test it."},
    {id:"copernicus",day:6,group:"S",kind:"person",term:"Copernicus",
     def:"A scientist who proposed that the sun, not the Earth, is the center of the solar system.",
     short:"Proposed the sun-centered solar system",
     hook:"Copernicus Came first with the idea. Galileo Got the telescope to back it up."},
    {id:"galileo",day:6,group:"S",kind:"person",term:"Galileo",
     def:"A scientist who used a telescope to support ideas about the planets and stars, backing up the heliocentric theory.",
     short:"Used a telescope to support heliocentric theory",
     hook:"Galileo = glass (the telescope lens). Spelling check: Galileo."},
    {id:"heliocentric",day:6,group:"S",kind:"idea",term:"Heliocentric",
     def:"The belief that the sun is the center of our solar system, challenging ancient geocentric (Earth-centered) models and reshaping modern astronomy.",
     short:"Sun-centered model of the solar system",
     hook:"Helio = sun (helium is named after the sun). Geo = Earth (like geography)."},
    {id:"newton",day:6,group:"S",kind:"person",term:"Sir Isaac Newton",
     def:"An English mathematician and physicist who formulated the laws of motion and universal gravitation, transforming our understanding of the cosmos.",
     short:"Laws of motion and gravity",
     hook:"Newton, apple, gravity. He explained why the planets move the way Copernicus and Galileo said they did."}
  ],

  /* Hand-written questions. a[0] is always the correct answer (the app shuffles). d = learn day it unlocks, or "C" for the connections day. */
  questions: [
    {t:["renaissance"],d:1,q:"The word “Renaissance” means…",a:["Rebirth","Revolution","Religion","Reform"],e:"Renaissance means rebirth: a renewed interest in art and learning."},
    {t:["constantinople"],d:1,q:"Constantinople was the capital of which empire before it was captured?",a:["The Byzantine Empire","The Ottoman Empire","The English Empire","The French Empire"],e:"It was the Byzantine capital until the Ottoman Empire captured it."},
    {t:["ottoman"],d:1,q:"Why did the Ottoman Empire matter so much to European traders?",a:["It controlled trade routes between Europe and Asia","It invented the printing press","It started the Reformation","It paid for Renaissance art"],e:"After capturing Constantinople, the Ottomans controlled key Europe–Asia trade routes."},
    {t:["turning"],d:1,q:"Which of these is the best example of a turning point?",a:["The invention of the printing press","A king eating breakfast","A painter finishing one sketch","A merchant selling cloth on a normal day"],e:"A turning point is a major event that changes the course of history."},
    {t:["humanism"],d:2,q:"A humanist thinker would be MOST interested in…",a:["What humans can achieve and create","Only what happens after death","Buying indulgences","Controlling trade routes"],e:"Humanism focused on human potential and achievements."},
    {t:["secular"],d:2,q:"Which painting subject is secular?",a:["A portrait of a wealthy merchant","An angel visiting Mary","A saint praying","A scene from the Bible"],e:"Secular means worldly or non-religious."},
    {t:["medici"],d:2,q:"How did the Medici family help the Renaissance?",a:["They used their wealth to support artists","They invented perspective","They wrote the 95 Theses","They captured Constantinople"],e:"The Medici were a wealthy Florence family who supported many artists."},
    {t:["inquiry"],d:2,q:"Which is the best example of inquiry?",a:["Asking a question, then observing and gathering evidence","Believing something just because it is old","Memorizing facts without asking questions","Guessing and never checking"],e:"Inquiry is asking questions and searching for truth through observation and evidence."},
    {t:["leonardo"],d:3,q:"Who painted the Mona Lisa?",a:["Leonardo da Vinci","Michelangelo","Galileo","Gutenberg"],e:"Leonardo da Vinci: artist, inventor, and scientist."},
    {t:["michelangelo"],d:3,q:"Who sculpted David and painted the Sistine Chapel ceiling?",a:["Michelangelo","Leonardo da Vinci","Martin Luther","Sir Isaac Newton"],e:"Michelangelo: marble (David) and ceiling (Sistine Chapel)."},
    {t:["perspective"],d:3,q:"An artist makes a road look like it stretches far into the distance on a flat canvas. This technique is…",a:["Perspective","Humanism","Inquiry","Secular"],e:"Perspective creates the appearance of depth on a flat surface."},
    {t:["press"],d:3,q:"What was the biggest effect of the printing press?",a:["Books and ideas spread faster and cheaper","Books became more expensive","Only priests were allowed to read","Artists stopped painting"],e:"The printing press made printing much faster and cheaper, so ideas spread quickly."},
    {t:["gutenberg","press"],d:3,q:"Which pair is matched correctly?",a:["Gutenberg: inventor. Printing press: his invention.","Printing press: inventor. Gutenberg: his invention.","Gutenberg: painter. Printing press: his painting.","Gutenberg: king. Printing press: his church."],e:"Gutenberg is the person. The printing press is the machine."},
    {t:["luther"],d:4,q:"Who wrote the 95 Theses criticizing the Catholic Church?",a:["Martin Luther","Martin Luther King Jr.","John Calvin","Henry VIII"],e:"Martin Luther, a German monk (1483–1546). Martin Luther King Jr. was a civil rights leader in the 1960s."},
    {t:["theses"],d:4,q:"When did Martin Luther post the 95 Theses?",a:["October 1517","July 1776","1453","1963"],e:"October 1517. (1453 is when Constantinople fell.)"},
    {t:["indulgence"],d:4,q:"Luther was especially angry about indulgences. What was an indulgence?",a:["A payment to the Church that people believed would forgive sins","A tax paid to the king","A translation of the Bible","A type of Renaissance painting"],e:"An indulgence was a payment people believed would forgive their sins."},
    {t:["reformation"],d:4,q:"What was the main RESULT of the Reformation?",a:["New Christian churches formed, separate from the Catholic Church","The Catholic Church took control of all of Europe","The Ottoman Empire captured Rome","Scientists proved the heliocentric theory"],e:"The Reformation led to new Christian churches separate from the Catholic Church."},
    {t:["protestant"],d:4,q:"A member of a Christian church that separated from the Roman Catholic Church was called a…",a:["Protestant","Humanist","Patron","Secular"],e:"Protestants “protested” against the Catholic Church."},
    {t:["worms"],d:4,q:"What happened at the Diet of Worms?",a:["Luther refused to take back his ideas","Luther invented the printing press","Henry VIII started his own church","The Ottomans captured Constantinople"],e:"In 1521 Luther was ordered to take back his ideas. He refused."},
    {t:["luther"],d:4,q:"Why did Luther want the Bible translated?",a:["So ordinary people could read it in their own language","So it could be sold for more money","So only priests could read it","So it would be shorter"],e:"Luther wanted people to read the Bible for themselves, in their own language."},
    {t:["indulgence"],d:4,q:"Three of these belong to the Renaissance art world. Which one doesn't belong?",a:["Indulgence","Perspective","Michelangelo","Medici family"],e:"An indulgence is a payment to the Church. It belongs with the Reformation."},
    {t:["henry"],d:5,q:"Why is Henry VIII part of the Reformation story?",a:["He broke England away from the Catholic Church and started the Church of England","He wrote the 95 Theses","He taught predestination","He led the Huguenots in France"],e:"Henry VIII broke away and started the Church of England."},
    {t:["calvin","predestination"],d:5,q:"Which idea is John Calvin best known for?",a:["Predestination","The heliocentric theory","Perspective","Selling indulgences"],e:"Calvin taught predestination: God has already decided who will be saved."},
    {t:["predestination"],d:5,q:"Predestination is the belief that…",a:["God has already decided who will be saved","Payments to the Church forgive sins","The sun is the center of the solar system","Humans should focus on life on Earth"],e:"Pre-destination: decided beforehand."},
    {t:["huguenots"],d:5,q:"Who were the Huguenots?",a:["French Protestants","English Catholics","Italian artists","Ottoman soldiers"],e:"The Huguenots were French Protestants who followed Calvin's ideas."},
    {t:["huguenots"],d:5,q:"Why did many Huguenots leave France?",a:["For religious freedom","To search for gold","To study art in Florence","To join the Ottoman Empire"],e:"France was Catholic and there were religious wars, so many Huguenots left for religious freedom."},
    {t:["art"],d:5,q:"How did the Reformation change art in Protestant areas?",a:["Artists painted daily life and civic pride instead of religious images","Artists made more statues of saints","All art was banned","Artists only painted popes"],e:"Protestants discouraged religious images, so artists turned to daily life and civic pride."},
    {t:["art"],d:5,q:"Why did some radical Protestant groups destroy Catholic art?",a:["They opposed religious images and praying to statues","They wanted to sell the paint","They preferred sculpture to painting","The pope ordered them to"],e:"They opposed religious images and discouraged followers from praying to statues."},
    {t:["map"],d:5,q:"On the map of the Reformation, which Protestant group held a LOT of land?",a:["Lutherans","Unitarians","The Medici","The Ottomans"],e:"Lutherans held a lot of land. Unitarians held very little."},
    {t:["map"],d:5,q:"On the map of the Reformation, which group held very LITTLE land?",a:["Unitarians","Lutherans","Catholics","Protestants as a whole"],e:"The Unitarians were found in only a small area."},
    {t:["copernicus"],d:6,q:"Who proposed that the sun, not the Earth, is the center of the solar system?",a:["Copernicus","Sir Isaac Newton","Leonardo da Vinci","John Calvin"],e:"Copernicus proposed it. Galileo later supported it with his telescope."},
    {t:["galileo"],d:6,q:"What tool did Galileo use to support the heliocentric theory?",a:["A telescope","A printing press","A microscope","A compass"],e:"Galileo used a telescope to study the planets and stars."},
    {t:["heliocentric"],d:6,q:"Heliocentric is to SUN as geocentric is to…",a:["Earth","Moon","Stars","Mars"],e:"Helio = sun. Geo = Earth."},
    {t:["newton"],d:6,q:"Sir Isaac Newton is known for…",a:["The laws of motion and universal gravitation","Painting the Mona Lisa","Starting the Church of England","Inventing the printing press"],e:"Newton formulated the laws of motion and universal gravitation."},
    {t:["scirev"],d:6,q:"What made the Scientific Revolution different from earlier ways of thinking?",a:["People used experiments and logic to understand the world","People relied only on ancient books","People stopped asking questions","The Church ran all the experiments"],e:"Experiments and logic, not just old authorities."},
    {t:["press","luther"],d:"C",q:"How did the printing press help the Reformation?",a:["It spread Luther's ideas quickly across Europe","It paid for Luther's travels","Luther invented it","It could only print indulgences"],e:"Printed copies of Luther's ideas spread fast. Without the press, the Reformation might have stayed small."},
    {t:["humanism","inquiry"],d:"C",q:"Humanism and inquiry both encouraged people to…",a:["Ask questions and think for themselves","Accept old ideas without question","Avoid art and learning","Stop reading books"],e:"That questioning attitude connects all three parts of this unit."},
    {t:["copernicus","galileo"],d:"C",q:"Which statement is correct?",a:["Copernicus proposed the sun-centered idea, and Galileo supported it with a telescope","Galileo proposed the sun-centered idea, and Copernicus supported it with a telescope","Newton proposed the sun-centered idea, and Luther supported it","Gutenberg proposed the sun-centered idea, and Newton printed it"],e:"Copernicus came first with the idea. Galileo got the telescope."},
    {t:["constantinople","ottoman","turning"],d:"C",q:"Which event is a turning point because it shifted control of trade between Europe and Asia?",a:["The Ottoman capture of Constantinople","The painting of the Mona Lisa","Newton's laws of motion","Henry VIII starting the Church of England"],e:"The Ottomans captured Constantinople and controlled the trade routes."},
    {t:[],d:"C",q:"What do the Renaissance, Reformation, and Scientific Revolution have in common?",a:["People questioned old authorities and old ideas","They were all started by the Ottoman Empire","They were all about trade routes","They all ended the Catholic Church"],e:"In art, religion, and science, people stopped just accepting what they were told."},
    {t:["newton"],d:"C",q:"Which person belongs to the Scientific Revolution?",a:["Sir Isaac Newton","Michelangelo","John Calvin","Henry VIII"],e:"Newton, Copernicus, and Galileo are the Scientific Revolution names."},
    {t:["calvin"],d:"C",q:"Which person belongs to the Reformation?",a:["John Calvin","Galileo","Leonardo da Vinci","Copernicus"],e:"Luther, Calvin, and Henry VIII are the Reformation names."},
    {t:["secular","humanism"],d:"C",q:"Secular art and humanism show that Renaissance people were becoming more interested in…",a:["Life on Earth and human achievement","Only the afterlife","Ending all trade","Destroying ancient books"],e:"Secular = worldly. Humanism = human potential."}
  ],

  /* Put-in-order questions. items are in the correct order (the app shuffles). */
  orders: [
    {q:"Put these in order, earliest first.",items:["The Renaissance begins in Italy","Gutenberg builds the printing press","Luther posts the 95 Theses","Newton explains gravity"],e:"Renaissance, then the printing press (1400s), then the 95 Theses (1517), then Newton (late 1600s)."},
    {q:"Put the Scientific Revolution in order: idea, evidence, laws.",items:["Copernicus proposes the sun-centered idea","Galileo supports it with his telescope","Newton explains motion and gravity"],e:"Copernicus had the idea, Galileo found evidence, Newton explained why it works."},
    {q:"Put the start of the Reformation in order.",items:["The Church sells indulgences","Luther posts the 95 Theses","Luther refuses to back down at the Diet of Worms","New Protestant churches form"],e:"Indulgences made Luther angry, he posted the theses (1517), refused to back down (1521), and new churches formed."}
  ],

  /* Shown on the connect day before the connections quiz. */
  bigPicture: {
    title:"One idea connects the whole unit",
    intro:"In art, in religion, and in science, people stopped simply accepting what they were told and started asking questions. That is humanism and inquiry at work.",
    chain:["Renaissance (art and learning)","Reformation (religion, 1517)","Scientific Revolution (science)"],
    sections:[
      {h:"A turning point opens the story",chain:["Ottomans capture Constantinople","Ottomans control Europe–Asia trade routes","Europe changes course"]},
      {h:"Money and ideas power the art",chain:["Medici wealth","Supports artists like Leonardo and Michelangelo","Art with perspective, humanism, secular subjects"]},
      {h:"The printing press spreads the protest",chain:["Church sells indulgences","Luther posts the 95 Theses","Printing press spreads his ideas","Protestant churches form"],
       note:"Those new churches include Lutherans, Calvin's followers (like the Huguenots in France), and Henry VIII's Church of England."},
      {h:"Science follows the same path",chain:["Copernicus: the idea","Galileo: telescope evidence","Newton: the laws that explain it"],
       note:"Heliocentric (sun-centered) replaced geocentric (Earth-centered)."}
    ]
  }
};
