/* Noah · Unit 3: Age of Colonization (with Age of Exploration vocab) · test Fri Oct 9, 2026 */
window.GUIDE = {
  id: "noah-unit3",
  student: "Noah",
  subject: "Unit 3",
  start: "2026-10-01",
  days: [
    {title:"Building empires", kind:"learn"},
    {title:"People, land and religion", kind:"learn"},
    {title:"Trade goes global", kind:"learn"},
    {title:"Colonization big picture", kind:"connect"},
    {title:"Ships and tools", kind:"learn"},
    {title:"Sailing east", kind:"learn"},
    {title:"Sailing west and around the world", kind:"learn"},
    {title:"Review day", kind:"final"},
    {title:"Test day", kind:"test"}
  ],
  groups: [
    {key:"E", name:"Empires"},
    {key:"P", name:"People and land"},
    {key:"T", name:"Global trade"},
    {key:"X", name:"Exploration"}
  ],

  /* day = which learn day (1-based) the card opens on. kind: person | place | idea. auto:false = no auto-generated questions. */
  terms: [
    {id:"colonization",day:1,group:"E",kind:"idea",term:"Colonization",
     def:"The claiming and settlement of foreign territories for the purpose of gaining resources for the mother country.",
     short:"Claiming foreign lands for resources",
     hook:"Colonization is the action; a colony is the place you end up with. The “mother country” is the one doing the claiming, like Spain or England."},
    {id:"colony",day:1,group:"E",kind:"idea",term:"Colony",
     def:"A territory that is under political control of another country",
     short:"Territory controlled by another country",
     hook:"Think of an ant colony far from the queen: it lives on its own land but still answers to her. The 13 colonies answered to England."},
    {id:"conquistador",day:1,group:"E",kind:"idea",term:"Conquistador",
     def:"A Spanish conqueror in the Americas",
     short:"Spanish conqueror in the Americas",
     hook:"Conquistador sounds like “conquer.” Famous ones: Cortés (took the Aztec Empire) and Pizarro (took the Inca Empire)."},
    {id:"encomienda",day:1,group:"E",kind:"idea",term:"Encomienda",
     def:"A system in which the Spanish king gave Spanish settlers the right to the labor of the Native Americans who lived in a particular area",
     short:"Spanish settlers given rights to Native labor",
     hook:"Encomienda comes from the Spanish word for “entrust.” The king “entrusted” Native people to settlers, who forced them to work. Spanish word = Spanish system."},

    {id:"indigenous",day:2,group:"P",kind:"idea",term:"Indigenous",
     def:"An original or native area where a person lives; the native populations of a country are called indigenous people.",
     short:"Native to a place; the original people",
     hook:"Indigenous = in the land first. The Aztec, Inca, and Taíno were indigenous to the Americas."},
    {id:"missionary",day:2,group:"P",kind:"idea",term:"Missionary",
     def:"A person sent to a foreign country to do religious work like convince people to join a religion or to help people that are sick, etc.",
     short:"Sent abroad to spread a religion",
     hook:"A missionary is on a mission for their religion."},
    {id:"resources",day:2,group:"P",kind:"idea",term:"Natural resources",plural:true,
     def:"Items that come from nature; they are not man made",
     short:"Useful things from nature, not man-made",
     hook:"Gold, silver, timber, furs, and farmland. Natural resources are what colonizers came for."},
    {id:"exploitation",day:2,group:"P",kind:"idea",term:"Exploitation",
     def:"The action of treating someone unfairly in order to benefit from their work and making use of and benefiting from natural resources",
     short:"Unfairly using people or resources for profit",
     hook:"Exploit = take advantage of. The encomienda system exploited indigenous people; mines exploited the land."},

    {id:"globalization",day:3,group:"T",kind:"idea",term:"Globalization",
     def:"The development of an increasingly integrated global economy through trade, finances, and communication.",
     short:"World economies becoming connected",
     hook:"Global = the whole globe. Your phone's parts come from many countries: that's globalization. It started with colonial trade routes."},
    {id:"dutch",day:3,group:"T",kind:"place",article:"the",term:"Dutch East India Company",
     def:"A company from the Netherlands that was primarily interested in trading with India for spices, indigo, and other natural resources",
     short:"Netherlands company trading in Asia for spices",
     hook:"Dutch = from the Netherlands. East India = where they went to trade for spices."},
    {id:"triangular",day:3,group:"T",kind:"place",article:"the",term:"Triangular Trade Route",
     def:"A massive trading system between Europe, Africa, and the Americas. Europe provided luxury items, guns, and alcohol to Africa and the Americas. Africa provided slaves to the Americas, and the Americas sent crops and furs to Europe thus creating The Triangular Trade Route.",
     short:"Three-way trade: Europe, Africa, the Americas",
     hook:"Three corners: Europe sends luxury items, guns, and alcohol; Africa → Americas (slaves); Americas → Europe (crops and furs)."},
    {id:"slavetrade",day:3,group:"T",kind:"place",article:"the",term:"Transatlantic Slave Trade",
     def:"The Transatlantic Slave Trade brought thousands of native Africans to the Americas to work as unpaid labor on large farms",
     short:"Enslaved Africans forced across the Atlantic",
     hook:"Trans-atlantic = across the Atlantic. Africa to the Americas, to work as unpaid labor on large farms."},
    {id:"middle",day:3,group:"T",kind:"place",article:"the",term:"Middle Passage",
     def:"The middle part of the Transatlantic Slave Trade from Africa to the Americas",
     short:"Africa-to-Americas part of the slave trade",
     hook:"Middle Passage = the middle part of the trip: Africa to the Americas."},
    /* Age of Exploration vocab, from Noah's handwritten sheet (spelling fixed only). */
    {id:"ageexp",day:4,group:"X",kind:"idea",article:"the",term:"Age of Exploration",
     def:"The period from 1400–1600 when Europeans sailed across the vast oceans to explore Asia, Africa, and the Americas.",
     short:"1400–1600: Europeans sail to explore",
     hook:"1400 to 1600: two hundred years of Europeans sailing to Asia, Africa, and the Americas. Exploring came first; colonizing came after."},
    {id:"caravel",day:4,group:"X",kind:"idea",term:"Caravel",
     def:"A new type of ship that was strong, fast, easily maneuverable, and able to sail against the wind.",
     short:"Strong, fast ship that sailed against the wind",
     hook:"Caravel = the car of the sea: strong, fast, and easy to steer."},
    {id:"lateen",day:4,group:"X",kind:"idea",term:"Lateen sails",plural:true,
     def:"Triangular sails that allowed ships to sail into the wind.",
     short:"Triangular sails for sailing into the wind",
     hook:"Lateen = triangle. A triangle sail lets the ship sail into the wind. Caravels used them."},
    {id:"astrolabe",day:4,group:"X",kind:"idea",term:"Astrolabe",
     def:"The astrolabe was invented by the Greeks and improved by the Arabs. It featured a way to measure the angles of the sun and stars in order to determine latitude, which is the distance of a place north or south of the equator.",
     short:"Measured sun and stars to find latitude",
     hook:"Astro = star (like astronaut). Look at the stars, find your latitude. Greeks invented it, Arabs improved it."},
    {id:"compass",day:4,group:"X",kind:"idea",term:"Magnetic compass",
     def:"This device was invented in the 1100s, and by the 1200s, the needle pivoted on a pin on a card that showed the direction.",
     short:"Needle on a pin that showed direction",
     hook:"Compass = direction. Astrolabe = latitude. The compass came first: 1100s, with the pin and card by the 1200s."},

    {id:"henry",day:5,group:"X",kind:"person",term:"Prince Henry the Navigator",
     def:"Third son of King John I of Portugal and Queen Philippa of Lancaster, who organized expeditions of sailors to explore the west coast of Africa.",
     short:"Portuguese prince who sent sailors down Africa's coast",
     hook:"A navigator who didn't sail himself: Henry organized the trips. Portugal + Africa's west coast."},
    {id:"cape",day:5,group:"X",kind:"place",article:"the",term:"Cape of Good Hope",
     def:"Southern tip of Africa.",
     short:"Southern tip of Africa",
     hook:"Getting around it gave sailors “good hope” of reaching India by sea."},
    {id:"dagama",day:5,group:"X",kind:"person",term:"Vasco da Gama",
     def:"A Portuguese explorer who searched for and found a trade route to India.",
     short:"Portuguese explorer who found a route to India",
     hook:"da Gama = da way to India. Portugal sailed east, around Africa."},
    {id:"zhenghe",day:5,group:"X",kind:"person",term:"Zheng He",
     def:"Chinese explorer, diplomat, and fleet admiral during the Chinese Ming dynasty. Completed 7 voyages throughout the Indian Ocean.",
     short:"Chinese Ming admiral, 7 Indian Ocean voyages",
     hook:"The one explorer on the list who isn't European. Zheng He: China, Ming dynasty, 7 voyages."},

    {id:"columbus",day:6,group:"X",kind:"person",term:"Christopher Columbus",
     def:"Italian explorer who sailed for Spain, trying to reach the Spice Islands, but inadvertently sailed in the wrong direction. 1492–1504.",
     short:"Italian explorer who sailed for Spain",
     hook:"Born in Italy, paid by Spain. Aimed for the Spice Islands, landed in the Americas instead. In 1492, Columbus sailed the ocean blue."},
    {id:"newworld",day:6,group:"X",kind:"place",article:"the",term:"New World",
     def:"The Western Hemisphere. It refers to the landmasses of North and South America that Columbus explored from 1492–1494.",
     short:"North and South America (Western Hemisphere)",
     hook:"New to Europeans, not to the indigenous people who already lived there."},
    {id:"demarcation",day:5,group:"X",kind:"place",article:"the",term:"Line of Demarcation",
     def:"Spain gets west, Portugal gets east.",
     short:"Spain gets west, Portugal gets east",
     hook:"Demarcation = marking a line. Spain West, Portugal East. That's why Columbus (Spain) went west and da Gama (Portugal) went east."},
    {id:"nwpassage",day:6,group:"X",kind:"place",article:"the",term:"Northwest Passage",
     def:"A way to sail through North America and then on to Asia by way of the Arctic Ocean.",
     short:"Route to Asia through North America and the Arctic",
     hook:"North + west: sail west over the top of North America, through the icy Arctic, to reach Asia."},

    {id:"magellan",day:6,group:"X",kind:"person",term:"Ferdinand Magellan",
     def:"A Portuguese explorer who served Spain and whose crew became the first to circumnavigate the globe from 1519–1522.",
     short:"His crew first circumnavigated the globe",
     hook:"Portuguese, but sailed for Spain (like Columbus: born one place, sailed for Spain). It was his CREW that made it all the way around."},
    {id:"strait",day:6,group:"X",kind:"place",article:"the",term:"Strait of Magellan",
     def:"A narrow, twisting water passage near the tip of South America that made travel to the Pacific Ocean from the Atlantic Ocean easier.",
     short:"Passage near South America's tip, Atlantic to Pacific",
     hook:"A strait is a narrow water passage. Magellan's strait = his shortcut from the Atlantic to the Pacific."},
    {id:"circum",day:6,group:"X",kind:"idea",term:"Circumnavigate",
     def:"Sail around the world. Magellan's crew.",
     short:"Sail around the world",
     hook:"Circum = around (like circle). Navigate = sail. Magellan's crew did it first."}
  ],

  /* Hand-written questions. a[0] is always the correct answer (the app shuffles). d = learn day it unlocks, or "C" for the connections day. */
  questions: [
    {t:["ageexp"],d:4,q:"When was the Age of Exploration?",a:["1400–1600","1100–1200","1519–1522","1800–1900"],e:"The Age of Exploration was the period from 1400–1600."},
    {t:["ageexp"],d:4,q:"During the Age of Exploration, Europeans sailed to explore…",a:["Asia, Africa, and the Americas","Only Europe","Only Antarctica","The Moon"],e:"Europeans sailed across the oceans to explore Asia, Africa, and the Americas."},
    {t:["caravel"],d:4,q:"What made the caravel a new and better ship?",a:["It was strong, fast, easily maneuverable, and able to sail against the wind","It was powered by steam","It could only sail with the wind","It was a small rowboat"],e:"The caravel was strong, fast, easily maneuverable, and could sail against the wind."},
    {t:["lateen"],d:4,q:"What shape were lateen sails?",a:["Triangular","Square","Round","Star-shaped"],e:"Lateen sails were triangular sails that let ships sail into the wind."},
    {t:["astrolabe"],d:4,q:"An astrolabe measured the angles of the sun and stars to find…",a:["Latitude","Direction","Speed","The depth of the ocean"],e:"The astrolabe measured the sun and stars to determine latitude."},
    {t:["astrolabe"],d:4,q:"Who invented the astrolabe, and who improved it?",a:["Invented by the Greeks, improved by the Arabs","Invented by the Arabs, improved by the Greeks","Invented by Spain, improved by Portugal","Invented by Zheng He, improved by Columbus"],e:"The astrolabe was invented by the Greeks and improved by the Arabs."},
    {t:["compass"],d:4,q:"Which tool showed sailors the direction?",a:["Magnetic compass","Astrolabe","Lateen sail","Caravel"],e:"The magnetic compass had a needle on a pin over a card that showed the direction."},
    {t:["compass","astrolabe"],d:4,q:"Which pair is matched correctly?",a:["Compass: direction. Astrolabe: latitude.","Compass: latitude. Astrolabe: direction.","Compass: a ship. Astrolabe: a sail.","Compass: a route to India. Astrolabe: a strait."],e:"The compass shows direction; the astrolabe finds latitude."},
    {t:["henry"],d:5,q:"What did Prince Henry the Navigator do?",a:["Organized expeditions to explore the west coast of Africa","Sailed around the world himself","Found the Strait of Magellan","Sailed for Spain to the New World"],e:"Prince Henry organized expeditions of sailors to explore the west coast of Africa."},
    {t:["henry"],d:5,q:"Prince Henry the Navigator was from which country?",a:["Portugal","Spain","Italy","China"],e:"He was the third son of King John I of Portugal."},
    {t:["cape"],d:5,q:"Where is the Cape of Good Hope?",a:["The southern tip of Africa","The tip of South America","The top of North America","The coast of India"],e:"The Cape of Good Hope is the southern tip of Africa."},
    {t:["dagama"],d:5,q:"Which explorer searched for and found a trade route to India?",a:["Vasco da Gama","Christopher Columbus","Ferdinand Magellan","Zheng He"],e:"Vasco da Gama, a Portuguese explorer, found a trade route to India."},
    {t:["zhenghe"],d:5,q:"Zheng He was an admiral from which country?",a:["China","Portugal","Spain","Italy"],e:"Zheng He was a Chinese explorer and fleet admiral during the Ming dynasty."},
    {t:["zhenghe"],d:5,q:"How many voyages did Zheng He complete in the Indian Ocean?",a:["7","1","3","95"],e:"Zheng He completed 7 voyages throughout the Indian Ocean."},
    {t:["columbus"],d:6,q:"Christopher Columbus was born in Italy but sailed for…",a:["Spain","Portugal","England","China"],e:"Columbus was an Italian explorer who sailed for Spain."},
    {t:["columbus"],d:6,q:"Where was Columbus trying to go?",a:["The Spice Islands","The North Pole","Africa's west coast","The Strait of Magellan"],e:"He was trying to reach the Spice Islands but sailed in the wrong direction."},
    {t:["newworld"],d:6,q:"The “New World” refers to…",a:["North and South America (the Western Hemisphere)","Europe","Asia and Africa","The Spice Islands"],e:"The New World is the Western Hemisphere: the landmasses of North and South America."},
    {t:["demarcation"],d:5,q:"Under the Line of Demarcation, which country got the land to the west?",a:["Spain","Portugal","China","Italy"],e:"Spain gets west, Portugal gets east."},
    {t:["demarcation"],d:5,q:"Under the Line of Demarcation, which country got the land to the east?",a:["Portugal","Spain","England","The Netherlands"],e:"Spain gets west, Portugal gets east."},
    {t:["nwpassage"],d:6,q:"The Northwest Passage was a way to sail to Asia through North America and the…",a:["Arctic Ocean","Indian Ocean","Mediterranean Sea","Strait of Magellan"],e:"It was a way to sail through North America and on to Asia by way of the Arctic Ocean."},
    {t:["magellan"],d:6,q:"Ferdinand Magellan was Portuguese, but he served…",a:["Spain","Portugal","China","England"],e:"Magellan was a Portuguese explorer who served Spain."},
    {t:["magellan","circum"],d:6,q:"Whose crew was the first to circumnavigate the globe?",a:["Ferdinand Magellan's","Christopher Columbus's","Vasco da Gama's","Zheng He's"],e:"Magellan's crew became the first to circumnavigate the globe, from 1519–1522."},
    {t:["circum"],d:6,q:"To circumnavigate means to…",a:["Sail around the world","Sail into the wind","Find latitude","Divide land between two countries"],e:"Circumnavigate means to sail around the world."},
    {t:["strait"],d:6,q:"The Strait of Magellan made it easier to travel from the Atlantic Ocean to the…",a:["Pacific Ocean","Indian Ocean","Arctic Ocean","Mediterranean Sea"],e:"It is a narrow, twisting passage near the tip of South America from the Atlantic to the Pacific."},
    {t:["strait","cape"],d:6,q:"Which statement is correct?",a:["The Strait of Magellan is near the tip of South America; the Cape of Good Hope is the southern tip of Africa","The Strait of Magellan is the southern tip of Africa; the Cape of Good Hope is near South America","Both are in Asia","Both are in the Arctic Ocean"],e:"Strait of Magellan = South America. Cape of Good Hope = Africa."},
    {t:["dagama","columbus","demarcation"],d:"C",q:"Which explorer sailed for Portugal, the country that got the EAST under the Line of Demarcation?",a:["Vasco da Gama","Christopher Columbus","Ferdinand Magellan","Zheng He"],e:"Vasco da Gama was Portuguese and found a route to India. Columbus and Magellan sailed for Spain."},
    {t:["zhenghe"],d:"C",q:"Which explorer doesn't belong with the others?",a:["Zheng He","Vasco da Gama","Christopher Columbus","Ferdinand Magellan"],e:"Zheng He was Chinese. The other three sailed for Portugal or Spain."},
    {t:["caravel","lateen","compass","astrolabe"],d:"C",q:"Caravels, lateen sails, the compass, and the astrolabe all helped explorers…",a:["Sail farther and find their way","Build colonies on land","Trade with the Dutch East India Company","Avoid the ocean"],e:"Better ships and tools made the long ocean voyages of the Age of Exploration possible."},
    {t:["columbus","newworld","conquistador"],d:"C",q:"Columbus sailed for Spain and explored the New World. Which Unit 3 term describes the Spanish conquerors who came to the Americas later?",a:["Conquistador","Missionary","Indigenous","Circumnavigate"],e:"A conquistador was a Spanish conqueror in the Americas."},
    {t:["ageexp","colonization"],d:"C",q:"Which came first?",a:["Exploring new lands (the Age of Exploration), then colonizing them","Colonizing new lands, then exploring them","The Transatlantic Slave Trade, then the caravel","The Dutch East India Company, then Prince Henry"],e:"Explorers found the routes and lands first; colonization followed."},
    {t:["colonization"],d:1,q:"Why did countries practice colonization?",a:["To gain resources for the mother country","To give land back to native people","To stop trading with other countries","To escape the Scientific Revolution"],e:"Colonization was about claiming land to gain resources for the mother country."},
    {t:["colony"],d:1,q:"Which is the best example of a colony?",a:["A territory in the Americas ruled by Spain","An independent kingdom in Africa","A city in Spain","A trade company's ship"],e:"A colony is a territory under the political control of another country."},
    {t:["colonization","colony"],d:1,q:"Which pair is matched correctly?",a:["Colonization: the process. Colony: the territory.","Colony: the process. Colonization: the territory.","Colonization: a Spanish conqueror. Colony: a trade route.","Colony: a religious worker. Colonization: a company."],e:"Colonization is the claiming and settling; the colony is the land that results."},
    {t:["conquistador"],d:1,q:"A conquistador was a…",a:["Spanish conqueror in the Americas","Dutch trader in Asia","French missionary","Native American leader"],e:"Conquistadors, like Cortés and Pizarro, were Spanish conquerors."},
    {t:["encomienda"],d:1,q:"Under the encomienda system, the Spanish king gave settlers the right to…",a:["The labor of Native Americans in an area","Trade spices with the East Indies","Start their own church","Sail the Middle Passage"],e:"Encomienda gave settlers the right to Native Americans' labor."},
    {t:["encomienda","conquistador"],d:1,q:"Which country do conquistadors and the encomienda system both belong to?",a:["Spain","The Netherlands","England","The Ottoman Empire"],e:"Both are Spanish words for parts of Spain's empire in the Americas."},

    {t:["indigenous"],d:2,q:"Which group was indigenous to the Americas?",a:["The Aztec","Spanish conquistadors","Dutch traders","English colonists"],e:"Indigenous people are the original people of a place, like the Aztec in Mexico."},
    {t:["missionary"],d:2,q:"What was the main goal of a missionary?",a:["To spread their religion and help people","To conquer land for the king","To trade spices","To run a plantation"],e:"Missionaries were sent to do religious work, like converting people or caring for the sick."},
    {t:["resources"],d:2,q:"Which of these is NOT a natural resource?",a:["A musket","Silver","Timber","Furs"],e:"A musket is man-made. Silver, timber, and furs come from nature."},
    {t:["exploitation"],d:2,q:"Forcing people to work in mines for little or no pay so someone else gets rich is an example of…",a:["Exploitation","Globalization","Missionary","Colonization"],e:"Exploitation is treating someone unfairly to benefit from their work."},
    {t:["exploitation","encomienda"],d:2,q:"Why is the encomienda system an example of exploitation?",a:["Settlers profited from Native Americans' forced labor","Native Americans were paid well for their work","It gave land back to indigenous people","It was a fair trade deal"],e:"Settlers benefited from labor they forced indigenous people to do."},
    {t:["resources","colonization"],d:2,q:"What did colonizers want most from their colonies?",a:["Natural resources like gold, silver, and crops","New languages to learn","Religious freedom for native people","Fewer trade routes"],e:"Colonization was about gaining resources for the mother country."},

    {t:["globalization"],d:3,q:"Globalization means…",a:["Economies around the world becoming more connected","One country taking over another","Spreading a religion","Making items from nature"],e:"Globalization is an increasingly connected world economy through trade, finance, and communication."},
    {t:["dutch"],d:3,q:"Where was the Dutch East India Company from?",a:["The Netherlands","Spain","India","England"],e:"It was a company from the Netherlands that traded with India."},
    {t:["dutch"],d:3,q:"What was the Dutch East India Company mainly trading for?",a:["Spices, indigo, and other natural resources","Slaves","Gold","Printed books"],e:"It was primarily interested in trading with India for spices, indigo, and other natural resources."},
    {t:["triangular"],d:3,q:"Which three regions made up the Triangular Trade Route?",a:["Europe, Africa, and the Americas","Europe, Asia, and Australia","Africa, Asia, and the Americas","Spain, France, and England"],e:"The three corners were Europe, Africa, and the Americas."},
    {t:["triangular"],d:3,q:"On the Triangular Trade Route, what did the Americas send to Europe?",a:["Crops and furs","Slaves","Guns and alcohol","Spices from India"],e:"The Americas sent crops and furs to Europe. Europe provided luxury items, guns, and alcohol."},
    {t:["middle"],d:3,q:"The Middle Passage was the part of the Transatlantic Slave Trade from…",a:["Africa to the Americas","Europe to Africa","The Americas to Europe","Europe to India"],e:"The Middle Passage was the middle part of the Transatlantic Slave Trade, from Africa to the Americas."},
    {t:["slavetrade"],d:3,q:"In the Transatlantic Slave Trade, native Africans were brought to the Americas to…",a:["Work as unpaid labor on large farms","Trade spices with India","Become missionaries","Rule new colonies"],e:"They were brought to work as unpaid labor on large farms."},

    {t:["triangular","slavetrade","middle"],d:"C",q:"Which statement about the Middle Passage is correct?",a:["It was the middle part of the Transatlantic Slave Trade, from Africa to the Americas","It is another name for the Dutch East India Company","It went from Europe to India","It carried crops and furs to Europe"],e:"The Middle Passage was the middle part of the Transatlantic Slave Trade, from Africa to the Americas."},
    {t:["exploitation","slavetrade","resources"],d:"C",q:"Which statement is correct?",a:["Exploitation can mean treating people unfairly to benefit from their work AND benefiting from natural resources","Exploitation only means using natural resources","Exploitation means spreading a religion","Missionaries were Spanish conquerors"],e:"The definition covers both: treating people unfairly to benefit from their work, and benefiting from natural resources."},
    {t:["globalization","triangular","dutch"],d:"C",q:"Which is the best example of early globalization?",a:["The triangular trade connecting Europe, Africa, and the Americas","A farmer growing food only for his family","A king ruling a small city","A monk copying a book by hand"],e:"Trade routes that connected continents were the start of a connected world economy."},
    {t:["conquistador","missionary"],d:"C",q:"Conquistadors and missionaries both came to the Americas. What was different about their goals?",a:["Conquistadors wanted land and gold; missionaries wanted to spread religion","Conquistadors spread religion; missionaries wanted gold","Both only wanted to trade spices","Both were indigenous people"],e:"Conquistadors conquered; missionaries converted and cared for people."},
    {t:["dutch"],d:"C",q:"Three of these connect Europe, Africa, and the Americas. Which one doesn't belong?",a:["Dutch East India Company","Middle Passage","Triangular Trade Route","Transatlantic Slave Trade"],e:"The Dutch East India Company traded with India, not across the Atlantic."},
        {t:["colony","indigenous"],d:"C",q:"What usually happened to indigenous people when a colony was set up on their land?",a:["They lost land and control, and many were forced to work","They became rulers of the mother country","They were paid for their resources","Nothing changed for them"],e:"Colonization took land and power from indigenous people and often exploited their labor."},
    {t:["globalization"],d:"C",q:"Globalization happens through which three things?",a:["Trade, finances, and communication","Conquest, religion, and art","Farming, mining, and fishing","Guns, alcohol, and luxury items"],e:"Globalization is an increasingly integrated global economy through trade, finances, and communication."}
  ],

  /* Put-in-order questions. items are in the correct order (the app shuffles). */
  orders: [
    {q:"Put these explorers in order, earliest first.",items:["Columbus sails for Spain (1492)","Magellan's crew circumnavigates the globe (1519–1522)"],e:"Columbus reached the New World in 1492; Magellan's crew sailed around the world from 1519–1522."},
    {q:"Put these navigation tools in order, earliest first.",items:["The magnetic compass is invented (1100s)","The compass needle pivots on a pin over a card (1200s)","The Age of Exploration begins (1400)"],e:"Compass in the 1100s, the pin and card by the 1200s, then the Age of Exploration from 1400–1600."},
    {q:"Follow the Triangular Trade Route. Put the legs in order, starting in Europe.",items:["Europe provides luxury items, guns, and alcohol","Africa provides slaves to the Americas (the Middle Passage)","The Americas send crops and furs to Europe"],e:"Europe → Africa → Americas → back to Europe."},
    {q:"Put the story of a Spanish colony in order.",items:["Conquistadors conquer indigenous empires","Spain claims the land as a colony","The king gives settlers encomiendas","Indigenous people are forced to work the land and mines"],e:"Conquest, then control, then the encomienda system, then exploitation of labor."}
  ],

  /* Shown on the connect day before the connections quiz. */
  bigPicture: {
    title:"One idea connects the whole unit",
    intro:"European countries claimed land around the world to get rich from its natural resources. That wealth came from exploiting people and land, and the trade it created started to connect the whole world.",
    chain:["Exploration (find the routes)","Colonization (claim the land)","Exploitation (people and resources)","Globalization (a connected world)"],
    sections:[
      {h:"Better ships and tools",chain:["Caravel with lateen sails","Compass for direction, astrolabe for latitude","Long ocean voyages (1400–1600)"]},
      {h:"Portugal east, Spain west",chain:["Line of Demarcation","Portugal: Prince Henry, Cape of Good Hope, Vasco da Gama to India","Spain: Columbus to the New World, Magellan's crew around the world"]},
      {h:"Spain takes the Americas",chain:["Conquistadors conquer","Colony is set up","Encomienda forces indigenous labor"],
       note:"Missionaries came too, to do religious work like convincing people to join a religion."},
      {h:"The Triangular Trade Route",chain:["Europe: luxury items, guns, alcohol","Africa: slaves to the Americas (the Middle Passage)","Americas: crops and furs to Europe"]},
      {h:"Trade with India",chain:["Dutch East India Company (Netherlands)","Trades with India","Spices, indigo, and other natural resources"]}
    ]
  }
};
